#============================#
# Panel Method from Katz & Plotkin
# Alwin Wang
#----------------------------#

#--- D1 Two-Dimensional Panel Methods                             ----
#  1. Grid generator for van de Vooren airfoil shapes, based on the formulas of Section 6.7. 
#     The program also calculates the exact chordwise velocity components and pressure 
#     coefficient for the purpose of comparison. All the two-dimensional codes (Programs 3–11) 
#     use the input generated by this subroutine.
VoorenAirfoil <- function() {
  AF <- data.frame()
  CP <- data.frame()
  # User Inputs
  # E  <- as.numeric(readline("Enter Thickness Coeff. E: "))
  # AK <- as.numeric(readline("Enter T.E. Angle Coeff. K: "))
  E  = 0.15
  AK = 5
  TL = 1.0
  A  = 2*TL*(E+1)^(AK-1)/(2^AK)
  # AL <- as.numeric(readline("Enter the Angle of Attack in Degrees: "))*pi/180
  # M  <- as.numeric(readline("Enter the Number of Airfoil Panels: "))
  AL = 10*pi/180
  M  = 10
  ITHETA = 360/M
  # Loop around circle plane to obtain the airfoil coordintes
  for (I in seq(0, 360, length.out = M)) {
    if (I == 0 | I == 360) {
      AF <- rbind(AF, data.frame(X = 1, Y = 0))
      CP <- rbind(CP, data.frame(X = 1, CP = 1))
    } else {
      TH=I*pi/180
      R1=sqrt((A*(cos(TH)-1))^2+(A*sin(TH))^2)
      R2=sqrt((A*(cos(TH)-E))^2+(A*sin(TH))^2)
    }
  }
}
#--- * 2D Panel Methods Based on Neumann BC                       ----
#  2. Discrete vortex, thin wing method, based on Section 11.1.1.
#  3. Constant strength source method (based on Section 11.2.1). Note that the matrix
#     solver (SUBROUTINE MATRX) is attached to this program only and is not listed
#     with Programs 4–11, for brevity.
#  4. Constant strength doublet method, based on Section 11.2.2.
#  5. Constant strength vortex method, based on Section 11.2.3.
#  6. Linear strength source method, based on Section 11.4.1.
#  7. Linear strength vortex method, based on Section 11.4.2.
#--- * 2D Panel Methods Based on Dirichlet BC                     ----
#  8. Constant strength doublet method, based on Section 11.3.2.
#  9. Constant strength source/doublet method, based on Section 11.3.1.
# 10. Linear strength doublet method, based on Section 11.5.2.
# 11. Quadratic strength doublet method, based on Section 11.6.2.

#--- D2 Three-Dimensional Programs                                ----
# 12. Influence of a three-dimensional, constant strength source/doublet element, based
#     on Sections 10.4.1 and 10.4.2.
# 13. Three-dimensional vortex lattice method for rectilinear lifting surfaces (with
#     ground effect), based on Section 12.3.
# 14. Three-dimensional panel method, using constant strength sources and doublets
#     with the Dirichlet boundary condition, based on Section 12.5.

#--- D3 Time-Dependent Programs                                   ----
# 15. Sudden acceleration of a flat plate at angle of attack (using a single lumped vortex
#     element). This program solves numerically the example of Section 13.7, but the
#     strengths of the airfoil vortex and the wake latest vortex are obtained algebraically
#     (and there is no matrix solution phase).
# 16. Unsteady motion of a thin rectangular lifting surface (solution is based on the model
#     of Section 13.12, which is an upgrade of the vortex lattice method of Program 13).

